'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    'sınıfı tarafından otomatik olarak oluşturuldu.
    'Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    'komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    '''<summary>
    '''  Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("agtvize.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        '''  CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property audi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property audii() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audii", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property bmw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property car_cartoon_gif_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("car-cartoon-gif-9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property checkered_flags_309794_960_720() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkered-flags-309794_960_720", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property europcar_berlin_car_rental_sport_utility_vehicle_ab_volvo_tire_car() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("europcar-berlin-car-rental-sport-utility-vehicle-ab-volvo-tire-car", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property finish_line_inc_running_clip_art_finish_line_png_transparent_image_thumbnail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("finish-line-inc-running-clip-art-finish-line-png-transparent-image-thumbnail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property imgbin_2015_dodge_dart_car_mazda_2016_dodge_dart_sxt_sport_dodge_Yt8EDLpU5yrxCK00Gkk6G5Mx7_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgbin-2015-dodge-dart-car-mazda-2016-dodge-dart-sxt-sport-dodge-Yt8EDLpU5yrxCK00"& _ 
                        "Gkk6G5Mx7_t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property mercedes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mercedes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property ngw1Yb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ngw1Yb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property pngresmi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngresmi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property posterler_yol_isaretleri_arka_plan_ile_asfalt_karayolu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("posterler-yol-isaretleri-arka-plan-ile-asfalt-karayolu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property posterler_yol_isaretleri_arka_plan_ile_asfalt_karayolu1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("posterler-yol-isaretleri-arka-plan-ile-asfalt-karayolu1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property race_car_animated_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("race-car-animated-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property siyah_png_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siyah-png-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property tesla() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tesla", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property toyota() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toyota", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property wolkswagen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wolkswagen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
